ALTER TABLE public.activecollab_credentials ADD CONSTRAINT activecollab_credentials_pkey PRIMARY KEY (id);
ALTER TABLE public.activecollab_sync_logs ADD CONSTRAINT activecollab_sync_logs_pkey PRIMARY KEY (id);
ALTER TABLE public.activecollab_task_data ADD CONSTRAINT activecollab_task_data_pkey PRIMARY KEY (id);
ALTER TABLE public.admin_google_drive_folders ADD CONSTRAINT admin_google_drive_folders_pkey PRIMARY KEY (id);
ALTER TABLE public.agent_memories ADD CONSTRAINT agent_memories_pkey PRIMARY KEY (id);
ALTER TABLE public.ai_agent_knowledge_selection ADD CONSTRAINT ai_agent_knowledge_selection_pkey PRIMARY KEY (id);
ALTER TABLE public.ai_agent_runs ADD CONSTRAINT ai_agent_runs_pkey PRIMARY KEY (id);
ALTER TABLE public.ai_agents ADD CONSTRAINT ai_agents_pkey PRIMARY KEY (id);
ALTER TABLE public.ai_configurations ADD CONSTRAINT ai_configurations_pkey PRIMARY KEY (id);
ALTER TABLE public.ai_generated_images ADD CONSTRAINT ai_generated_images_pkey PRIMARY KEY (id);
ALTER TABLE public.ai_shared_resources ADD CONSTRAINT ai_shared_resources_pkey PRIMARY KEY (id);
ALTER TABLE public.brand_analytics_data ADD CONSTRAINT brand_analytics_data_pkey PRIMARY KEY (id);
ALTER TABLE public.brand_analytics_integrations ADD CONSTRAINT brand_analytics_integrations_pkey PRIMARY KEY (id);
ALTER TABLE public.brand_file_comments ADD CONSTRAINT brand_file_comments_pkey PRIMARY KEY (id);
ALTER TABLE public.brand_generated_posts ADD CONSTRAINT brand_generated_posts_pkey PRIMARY KEY (id);
ALTER TABLE public.brand_knowledge_files ADD CONSTRAINT brand_knowledge_files_pkey PRIMARY KEY (id);
ALTER TABLE public.brand_kpis ADD CONSTRAINT brand_kpis_pkey PRIMARY KEY (id);
ALTER TABLE public.brands ADD CONSTRAINT brands_pkey PRIMARY KEY (id);
ALTER TABLE public.clients ADD CONSTRAINT clients_pkey PRIMARY KEY (id);
ALTER TABLE public.code_analysis_results ADD CONSTRAINT code_analysis_results_pkey PRIMARY KEY (id);
ALTER TABLE public.code_generation_templates ADD CONSTRAINT code_generation_templates_pkey PRIMARY KEY (id);
ALTER TABLE public.code_repositories ADD CONSTRAINT code_repositories_pkey PRIMARY KEY (id);
ALTER TABLE public.collabai_agents ADD CONSTRAINT collabai_agents_pkey PRIMARY KEY (id);
ALTER TABLE public.contacts ADD CONSTRAINT contacts_pkey PRIMARY KEY (id);
ALTER TABLE public.content_performance_metrics ADD CONSTRAINT content_performance_metrics_pkey PRIMARY KEY (id);
ALTER TABLE public.control_tower_api_keys ADD CONSTRAINT control_tower_api_keys_pkey PRIMARY KEY (id);
ALTER TABLE public.control_tower_sync_logs ADD CONSTRAINT control_tower_sync_logs_pkey PRIMARY KEY (id);
ALTER TABLE public.deals ADD CONSTRAINT deals_pkey PRIMARY KEY (id);
ALTER TABLE public.documentation_output_config ADD CONSTRAINT documentation_output_config_pkey PRIMARY KEY (id);
ALTER TABLE public.documentation_repository_links ADD CONSTRAINT documentation_repository_links_pkey PRIMARY KEY (id);
ALTER TABLE public.documentation_rules ADD CONSTRAINT documentation_rules_pkey PRIMARY KEY (id);
ALTER TABLE public.documentation_templates ADD CONSTRAINT documentation_templates_pkey PRIMARY KEY (id);
ALTER TABLE public.employee_user_mapping ADD CONSTRAINT employee_user_mapping_pkey PRIMARY KEY (id);
ALTER TABLE public.employees ADD CONSTRAINT employees_pkey PRIMARY KEY (id);
ALTER TABLE public.feedback_comments ADD CONSTRAINT feedback_comments_pkey PRIMARY KEY (id);
ALTER TABLE public.feedback_reports ADD CONSTRAINT feedback_reports_pkey PRIMARY KEY (id);
ALTER TABLE public.gemini_videos ADD CONSTRAINT gemini_videos_pkey PRIMARY KEY (id);
ALTER TABLE public.generated_posts ADD CONSTRAINT generated_posts_pkey PRIMARY KEY (id);
ALTER TABLE public.gohighlevel_contacts ADD CONSTRAINT gohighlevel_contacts_pkey PRIMARY KEY (id);
ALTER TABLE public.gohighlevel_integrations ADD CONSTRAINT gohighlevel_integrations_pkey PRIMARY KEY (id);
ALTER TABLE public.google_drive_settings ADD CONSTRAINT google_drive_settings_pkey PRIMARY KEY (id);
ALTER TABLE public.hackathon_events ADD CONSTRAINT hackathon_events_pkey PRIMARY KEY (id);
ALTER TABLE public.hackathon_judges ADD CONSTRAINT hackathon_judges_pkey PRIMARY KEY (id);
ALTER TABLE public.hackathon_participants ADD CONSTRAINT hackathon_participants_pkey PRIMARY KEY (id);
ALTER TABLE public.hackathon_scores ADD CONSTRAINT hackathon_scores_pkey PRIMARY KEY (id);
ALTER TABLE public.hackathon_submissions ADD CONSTRAINT hackathon_submissions_pkey PRIMARY KEY (id);
ALTER TABLE public.hackathon_team_members ADD CONSTRAINT hackathon_team_members_pkey PRIMARY KEY (id);
ALTER TABLE public.hackathon_teams ADD CONSTRAINT hackathon_teams_pkey PRIMARY KEY (id);
ALTER TABLE public.influencer_style_library ADD CONSTRAINT influencer_style_library_pkey PRIMARY KEY (id);
ALTER TABLE public.integration_logs ADD CONSTRAINT integration_logs_pkey PRIMARY KEY (id);
ALTER TABLE public.keyword_blog_usage ADD CONSTRAINT keyword_blog_usage_pkey PRIMARY KEY (id);
ALTER TABLE public.keyword_ranking_history ADD CONSTRAINT keyword_ranking_history_pkey PRIMARY KEY (id);
ALTER TABLE public.keyword_research ADD CONSTRAINT keyword_research_pkey PRIMARY KEY (id);
ALTER TABLE public.keyword_suggestions ADD CONSTRAINT keyword_suggestions_pkey PRIMARY KEY (id);
ALTER TABLE public.knowledge_base ADD CONSTRAINT knowledge_base_pkey PRIMARY KEY (id);
ALTER TABLE public.knowledge_base_categories ADD CONSTRAINT knowledge_base_categories_pkey PRIMARY KEY (id);
ALTER TABLE public.knowledge_base_files ADD CONSTRAINT knowledge_base_files_pkey PRIMARY KEY (id);
ALTER TABLE public.knowledge_files ADD CONSTRAINT knowledge_files_pkey PRIMARY KEY (id);
ALTER TABLE public.knowledge_sources ADD CONSTRAINT knowledge_sources_pkey PRIMARY KEY (id);
ALTER TABLE public.leader_uploads ADD CONSTRAINT leader_uploads_pkey PRIMARY KEY (id);
ALTER TABLE public.linkedin_agent_templates ADD CONSTRAINT linkedin_agent_templates_pkey PRIMARY KEY (id);
ALTER TABLE public.linkedin_analytics_upload ADD CONSTRAINT linkedin_analytics_upload_pkey PRIMARY KEY (id);
ALTER TABLE public.linkedin_content_metadata ADD CONSTRAINT linkedin_content_metadata_pkey PRIMARY KEY (id);
ALTER TABLE public.marketing_team_members ADD CONSTRAINT marketing_team_members_pkey PRIMARY KEY (id);
ALTER TABLE public.n8n_workflow_configs ADD CONSTRAINT n8n_workflow_configs_pkey PRIMARY KEY (id);
ALTER TABLE public.n8n_workflow_executions ADD CONSTRAINT n8n_workflow_executions_pkey PRIMARY KEY (id);
ALTER TABLE public.newsletter_categories ADD CONSTRAINT newsletter_categories_pkey PRIMARY KEY (id);
ALTER TABLE public.newsletter_sources ADD CONSTRAINT newsletter_sources_pkey PRIMARY KEY (id);
ALTER TABLE public.organization_integrations ADD CONSTRAINT organization_integrations_pkey PRIMARY KEY (id);
ALTER TABLE public.organizations ADD CONSTRAINT organizations_pkey PRIMARY KEY (id);
ALTER TABLE public.perplexity_settings ADD CONSTRAINT perplexity_settings_pkey PRIMARY KEY (id);
ALTER TABLE public.pod_members ADD CONSTRAINT pod_members_pkey PRIMARY KEY (id);
ALTER TABLE public.pods ADD CONSTRAINT pods_pkey PRIMARY KEY (id);
ALTER TABLE public.post_agent_references ADD CONSTRAINT post_agent_references_pkey PRIMARY KEY (id);
ALTER TABLE public.project_knowledge_files ADD CONSTRAINT project_knowledge_files_pkey PRIMARY KEY (id);
ALTER TABLE public.project_meetings ADD CONSTRAINT project_meetings_pkey PRIMARY KEY (id);
ALTER TABLE public.project_task_comments ADD CONSTRAINT project_task_comments_pkey PRIMARY KEY (id);
ALTER TABLE public.project_tasks ADD CONSTRAINT project_tasks_pkey PRIMARY KEY (id);
ALTER TABLE public.projects ADD CONSTRAINT projects_pkey PRIMARY KEY (id);
ALTER TABLE public.quote_items ADD CONSTRAINT quote_items_pkey PRIMARY KEY (id);
ALTER TABLE public.quotes ADD CONSTRAINT quotes_pkey PRIMARY KEY (id);
ALTER TABLE public.role_permissions ADD CONSTRAINT role_permissions_pkey PRIMARY KEY (id);
ALTER TABLE public.seo_blog_content ADD CONSTRAINT seo_blog_content_pkey PRIMARY KEY (id);
ALTER TABLE public.seo_reference_summaries ADD CONSTRAINT seo_reference_summaries_pkey PRIMARY KEY (id);
ALTER TABLE public.sora_videos ADD CONSTRAINT sora_videos_pkey PRIMARY KEY (id);
ALTER TABLE public.team_daily_summaries ADD CONSTRAINT team_daily_summaries_pkey PRIMARY KEY (id);
ALTER TABLE public.team_eod_submissions ADD CONSTRAINT team_eod_submissions_pkey PRIMARY KEY (id);
ALTER TABLE public.team_members ADD CONSTRAINT team_members_pkey PRIMARY KEY (id);
ALTER TABLE public.teams ADD CONSTRAINT teams_pkey PRIMARY KEY (id);
ALTER TABLE public.testimonials ADD CONSTRAINT testimonials_pkey PRIMARY KEY (id);
ALTER TABLE public.thought_leaders ADD CONSTRAINT thought_leaders_pkey PRIMARY KEY (id);
ALTER TABLE public.user_accountability_chart ADD CONSTRAINT user_accountability_chart_pkey PRIMARY KEY (id);
ALTER TABLE public.user_activecollab_settings ADD CONSTRAINT user_activecollab_settings_pkey PRIMARY KEY (id);
ALTER TABLE public.user_brands ADD CONSTRAINT user_brands_pkey PRIMARY KEY (id);
ALTER TABLE public.user_google_tokens ADD CONSTRAINT user_google_tokens_pkey PRIMARY KEY (id);
ALTER TABLE public.user_permissions ADD CONSTRAINT user_permissions_pkey PRIMARY KEY (id);
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_pkey PRIMARY KEY (id);
ALTER TABLE public.users ADD CONSTRAINT users_pkey PRIMARY KEY (id);
ALTER TABLE public.vision_examples ADD CONSTRAINT vision_examples_pkey PRIMARY KEY (id);
ALTER TABLE public.weekly_client_summary ADD CONSTRAINT weekly_client_summary_pkey PRIMARY KEY (id);
ALTER TABLE public.weekly_content_ideas ADD CONSTRAINT weekly_content_ideas_pkey PRIMARY KEY (id);
ALTER TABLE public.weekly_trends ADD CONSTRAINT weekly_trends_pkey PRIMARY KEY (id);
ALTER TABLE public.ai_agent_knowledge_selection ADD CONSTRAINT ai_agent_knowledge_selection_agent_id_category_id_key UNIQUE (agent_id, category_id);
ALTER TABLE public.ai_agents ADD CONSTRAINT ai_agents_slug_key UNIQUE (slug);
ALTER TABLE public.brands ADD CONSTRAINT brands_slug_key UNIQUE (slug);
ALTER TABLE public.clients ADD CONSTRAINT clients_slug_key UNIQUE (slug);
ALTER TABLE public.employee_user_mapping ADD CONSTRAINT employee_user_mapping_employee_id_user_id_key UNIQUE (employee_id, user_id);
ALTER TABLE public.employees ADD CONSTRAINT employees_employee_id_key UNIQUE (employee_id);
ALTER TABLE public.gohighlevel_contacts ADD CONSTRAINT gohighlevel_contacts_ghl_id_key UNIQUE (ghl_id);
ALTER TABLE public.hackathon_judges ADD CONSTRAINT hackathon_judges_event_id_user_id_key UNIQUE (event_id, user_id);
ALTER TABLE public.hackathon_participants ADD CONSTRAINT hackathon_participants_event_id_user_id_key UNIQUE (event_id, user_id);
ALTER TABLE public.hackathon_team_members ADD CONSTRAINT hackathon_team_members_team_id_participant_id_key UNIQUE (team_id, participant_id);
ALTER TABLE public.marketing_team_members ADD CONSTRAINT marketing_team_members_user_id_brand_id_key UNIQUE (user_id, brand_id);
ALTER TABLE public.organizations ADD CONSTRAINT organizations_slug_key UNIQUE (slug);
ALTER TABLE public.pod_members ADD CONSTRAINT pod_members_pod_id_employee_id_key UNIQUE (pod_id, employee_id);
ALTER TABLE public.projects ADD CONSTRAINT projects_slug_key UNIQUE (slug);
ALTER TABLE public.team_daily_summaries ADD CONSTRAINT team_daily_summaries_summary_date_key UNIQUE (summary_date);
ALTER TABLE public.team_eod_submissions ADD CONSTRAINT team_eod_submissions_user_id_submission_date_key UNIQUE (user_id, submission_date);
ALTER TABLE public.team_members ADD CONSTRAINT team_members_team_id_user_id_key UNIQUE (team_id, user_id);
ALTER TABLE public.thought_leaders ADD CONSTRAINT thought_leaders_slug_key UNIQUE (slug);
ALTER TABLE public.user_activecollab_settings ADD CONSTRAINT user_activecollab_settings_user_id_key UNIQUE (user_id);
ALTER TABLE public.user_brands ADD CONSTRAINT user_brands_user_id_brand_id_key UNIQUE (user_id, brand_id);
ALTER TABLE public.user_google_tokens ADD CONSTRAINT user_google_tokens_user_id_key UNIQUE (user_id);
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_user_id_role_key UNIQUE (user_id, role);
ALTER TABLE public.users ADD CONSTRAINT users_email_key UNIQUE (email);
ALTER TABLE public.brands ADD CONSTRAINT brands_status_check CHECK ((status = ANY (ARRAY['active'::text, 'inactive'::text, 'archived'::text])));
ALTER TABLE public.brands ADD CONSTRAINT brands_type_check CHECK ((type = ANY (ARRAY['internal'::text, 'client'::text])));
ALTER TABLE public.seo_blog_content ADD CONSTRAINT seo_blog_content_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'generating'::text, 'validated'::text, 'failed'::text, 'published'::text])));
ALTER TABLE public.agent_memories ADD CONSTRAINT agent_memories_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES ai_agents(id);
ALTER TABLE public.ai_agent_knowledge_selection ADD CONSTRAINT ai_agent_knowledge_selection_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES ai_agents(id) ON DELETE CASCADE;
ALTER TABLE public.ai_agent_knowledge_selection ADD CONSTRAINT ai_agent_knowledge_selection_category_id_fkey FOREIGN KEY (category_id) REFERENCES knowledge_base_categories(id) ON DELETE CASCADE;
ALTER TABLE public.ai_agent_runs ADD CONSTRAINT ai_agent_runs_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES ai_agents(id);
ALTER TABLE public.ai_agent_runs ADD CONSTRAINT ai_agent_runs_executed_by_fkey FOREIGN KEY (executed_by) REFERENCES users(id);
ALTER TABLE public.ai_agents ADD CONSTRAINT ai_agents_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE public.ai_generated_images ADD CONSTRAINT ai_generated_images_generated_by_fkey FOREIGN KEY (generated_by) REFERENCES users(id);
ALTER TABLE public.ai_shared_resources ADD CONSTRAINT ai_shared_resources_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE public.brand_analytics_data ADD CONSTRAINT brand_analytics_data_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES brands(id);
ALTER TABLE public.brand_analytics_integrations ADD CONSTRAINT brand_analytics_integrations_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES brands(id);
ALTER TABLE public.brand_file_comments ADD CONSTRAINT brand_file_comments_file_id_fkey FOREIGN KEY (file_id) REFERENCES brand_knowledge_files(id) ON DELETE CASCADE;
ALTER TABLE public.brand_file_comments ADD CONSTRAINT brand_file_comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE public.brand_generated_posts ADD CONSTRAINT brand_generated_posts_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES ai_agents(id);
ALTER TABLE public.brand_generated_posts ADD CONSTRAINT brand_generated_posts_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES brands(id);
ALTER TABLE public.brand_generated_posts ADD CONSTRAINT brand_generated_posts_generated_by_fkey FOREIGN KEY (generated_by) REFERENCES users(id);
ALTER TABLE public.brand_knowledge_files ADD CONSTRAINT brand_knowledge_files_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES brands(id) ON DELETE CASCADE;
ALTER TABLE public.brand_knowledge_files ADD CONSTRAINT brand_knowledge_files_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES users(id);
ALTER TABLE public.brand_kpis ADD CONSTRAINT brand_kpis_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES brands(id) ON DELETE CASCADE;
ALTER TABLE public.brands ADD CONSTRAINT brands_co_owner_id_fkey FOREIGN KEY (co_owner_id) REFERENCES users(id);
ALTER TABLE public.brands ADD CONSTRAINT brands_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE public.brands ADD CONSTRAINT brands_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id);
ALTER TABLE public.brands ADD CONSTRAINT brands_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES users(id);
ALTER TABLE public.code_analysis_results ADD CONSTRAINT code_analysis_results_repository_id_fkey FOREIGN KEY (repository_id) REFERENCES code_repositories(id);
ALTER TABLE public.contacts ADD CONSTRAINT contacts_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id);
ALTER TABLE public.deals ADD CONSTRAINT deals_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES users(id);
ALTER TABLE public.deals ADD CONSTRAINT deals_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id);
ALTER TABLE public.documentation_repository_links ADD CONSTRAINT documentation_repository_links_repository_id_fkey FOREIGN KEY (repository_id) REFERENCES code_repositories(id);
ALTER TABLE public.employee_user_mapping ADD CONSTRAINT employee_user_mapping_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES employees(id);
ALTER TABLE public.employee_user_mapping ADD CONSTRAINT employee_user_mapping_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE public.feedback_comments ADD CONSTRAINT feedback_comments_feedback_id_fkey FOREIGN KEY (feedback_id) REFERENCES feedback_reports(id) ON DELETE CASCADE;
ALTER TABLE public.feedback_comments ADD CONSTRAINT feedback_comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE public.feedback_reports ADD CONSTRAINT feedback_reports_submitted_by_fkey FOREIGN KEY (submitted_by) REFERENCES users(id);
ALTER TABLE public.feedback_reports ADD CONSTRAINT feedback_reports_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE public.gemini_videos ADD CONSTRAINT gemini_videos_generated_by_fkey FOREIGN KEY (generated_by) REFERENCES users(id);
ALTER TABLE public.generated_posts ADD CONSTRAINT generated_posts_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES ai_agents(id);
ALTER TABLE public.generated_posts ADD CONSTRAINT generated_posts_generated_by_fkey FOREIGN KEY (generated_by) REFERENCES users(id);
ALTER TABLE public.generated_posts ADD CONSTRAINT generated_posts_leader_id_fkey FOREIGN KEY (leader_id) REFERENCES thought_leaders(id);
ALTER TABLE public.google_drive_settings ADD CONSTRAINT google_drive_settings_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES brands(id);
ALTER TABLE public.hackathon_events ADD CONSTRAINT hackathon_events_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE public.hackathon_judges ADD CONSTRAINT hackathon_judges_event_id_fkey FOREIGN KEY (event_id) REFERENCES hackathon_events(id);
ALTER TABLE public.hackathon_judges ADD CONSTRAINT hackathon_judges_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE public.hackathon_participants ADD CONSTRAINT hackathon_participants_event_id_fkey FOREIGN KEY (event_id) REFERENCES hackathon_events(id) ON DELETE CASCADE;
ALTER TABLE public.hackathon_participants ADD CONSTRAINT hackathon_participants_team_id_fkey FOREIGN KEY (team_id) REFERENCES hackathon_teams(id);
ALTER TABLE public.hackathon_participants ADD CONSTRAINT hackathon_participants_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE public.hackathon_scores ADD CONSTRAINT hackathon_scores_judge_id_fkey FOREIGN KEY (judge_id) REFERENCES hackathon_judges(id);
ALTER TABLE public.hackathon_scores ADD CONSTRAINT hackathon_scores_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES hackathon_submissions(id);
ALTER TABLE public.hackathon_submissions ADD CONSTRAINT hackathon_submissions_team_id_fkey FOREIGN KEY (team_id) REFERENCES hackathon_teams(id);
ALTER TABLE public.hackathon_team_members ADD CONSTRAINT hackathon_team_members_participant_id_fkey FOREIGN KEY (participant_id) REFERENCES hackathon_participants(id);
ALTER TABLE public.hackathon_team_members ADD CONSTRAINT hackathon_team_members_team_id_fkey FOREIGN KEY (team_id) REFERENCES hackathon_teams(id) ON DELETE CASCADE;
ALTER TABLE public.hackathon_teams ADD CONSTRAINT hackathon_teams_event_id_fkey FOREIGN KEY (event_id) REFERENCES hackathon_events(id) ON DELETE CASCADE;
ALTER TABLE public.hackathon_teams ADD CONSTRAINT hackathon_teams_team_lead_id_fkey FOREIGN KEY (team_lead_id) REFERENCES users(id);
ALTER TABLE public.keyword_blog_usage ADD CONSTRAINT keyword_blog_usage_keyword_id_fkey FOREIGN KEY (keyword_id) REFERENCES keyword_research(id) ON DELETE CASCADE;
ALTER TABLE public.keyword_ranking_history ADD CONSTRAINT keyword_ranking_history_keyword_id_fkey FOREIGN KEY (keyword_id) REFERENCES keyword_research(id);
ALTER TABLE public.keyword_research ADD CONSTRAINT keyword_research_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES brands(id) ON DELETE CASCADE;
ALTER TABLE public.knowledge_base ADD CONSTRAINT knowledge_base_category_id_fkey FOREIGN KEY (category_id) REFERENCES knowledge_base_categories(id);
ALTER TABLE public.knowledge_base ADD CONSTRAINT knowledge_base_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE public.knowledge_base_categories ADD CONSTRAINT knowledge_base_categories_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES knowledge_base_categories(id);
ALTER TABLE public.knowledge_base_files ADD CONSTRAINT knowledge_base_files_category_id_fkey FOREIGN KEY (category_id) REFERENCES knowledge_base_categories(id);
ALTER TABLE public.knowledge_base_files ADD CONSTRAINT knowledge_base_files_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES users(id);
ALTER TABLE public.knowledge_files ADD CONSTRAINT knowledge_files_source_id_fkey FOREIGN KEY (source_id) REFERENCES knowledge_sources(id) ON DELETE CASCADE;
ALTER TABLE public.knowledge_files ADD CONSTRAINT knowledge_files_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES users(id);
ALTER TABLE public.knowledge_sources ADD CONSTRAINT knowledge_sources_category_id_fkey FOREIGN KEY (category_id) REFERENCES knowledge_base_categories(id) ON DELETE SET NULL;
ALTER TABLE public.knowledge_sources ADD CONSTRAINT knowledge_sources_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE public.leader_uploads ADD CONSTRAINT leader_uploads_leader_id_fkey FOREIGN KEY (leader_id) REFERENCES thought_leaders(id) ON DELETE CASCADE;
ALTER TABLE public.leader_uploads ADD CONSTRAINT leader_uploads_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES users(id);
ALTER TABLE public.linkedin_analytics_upload ADD CONSTRAINT linkedin_analytics_upload_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES brands(id);
ALTER TABLE public.marketing_team_members ADD CONSTRAINT marketing_team_members_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES brands(id);
ALTER TABLE public.marketing_team_members ADD CONSTRAINT marketing_team_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE public.n8n_workflow_executions ADD CONSTRAINT n8n_workflow_executions_workflow_id_fkey FOREIGN KEY (workflow_id) REFERENCES n8n_workflow_configs(id);
ALTER TABLE public.organization_integrations ADD CONSTRAINT organization_integrations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id);
ALTER TABLE public.pod_members ADD CONSTRAINT pod_members_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES employees(id);
ALTER TABLE public.pod_members ADD CONSTRAINT pod_members_pod_id_fkey FOREIGN KEY (pod_id) REFERENCES pods(id) ON DELETE CASCADE;
ALTER TABLE public.pods ADD CONSTRAINT pods_pod_lead_id_fkey FOREIGN KEY (pod_lead_id) REFERENCES employees(id);
ALTER TABLE public.post_agent_references ADD CONSTRAINT post_agent_references_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES ai_agents(id);
ALTER TABLE public.project_knowledge_files ADD CONSTRAINT project_knowledge_files_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
ALTER TABLE public.project_knowledge_files ADD CONSTRAINT project_knowledge_files_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES users(id);
ALTER TABLE public.project_meetings ADD CONSTRAINT project_meetings_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE public.project_meetings ADD CONSTRAINT project_meetings_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id);
ALTER TABLE public.project_task_comments ADD CONSTRAINT project_task_comments_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE public.project_task_comments ADD CONSTRAINT project_task_comments_task_id_fkey FOREIGN KEY (task_id) REFERENCES project_tasks(id) ON DELETE CASCADE;
ALTER TABLE public.project_tasks ADD CONSTRAINT project_tasks_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES users(id);
ALTER TABLE public.project_tasks ADD CONSTRAINT project_tasks_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
ALTER TABLE public.projects ADD CONSTRAINT projects_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id);
ALTER TABLE public.projects ADD CONSTRAINT projects_project_manager_id_fkey FOREIGN KEY (project_manager_id) REFERENCES users(id);
ALTER TABLE public.quote_items ADD CONSTRAINT quote_items_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES quotes(id) ON DELETE CASCADE;
ALTER TABLE public.quotes ADD CONSTRAINT quotes_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id);
ALTER TABLE public.quotes ADD CONSTRAINT quotes_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE public.seo_blog_content ADD CONSTRAINT seo_blog_content_author_id_fkey FOREIGN KEY (author_id) REFERENCES users(id);
ALTER TABLE public.seo_blog_content ADD CONSTRAINT seo_blog_content_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES brands(id);
ALTER TABLE public.seo_blog_content ADD CONSTRAINT seo_blog_content_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.sora_videos ADD CONSTRAINT sora_videos_generated_by_fkey FOREIGN KEY (generated_by) REFERENCES users(id);
ALTER TABLE public.team_eod_submissions ADD CONSTRAINT team_eod_submissions_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE public.team_members ADD CONSTRAINT team_members_team_id_fkey FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.team_members ADD CONSTRAINT team_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE public.teams ADD CONSTRAINT teams_team_lead_id_fkey FOREIGN KEY (team_lead_id) REFERENCES users(id);
ALTER TABLE public.thought_leaders ADD CONSTRAINT thought_leaders_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES ai_agents(id);
ALTER TABLE public.thought_leaders ADD CONSTRAINT thought_leaders_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE public.user_accountability_chart ADD CONSTRAINT user_accountability_chart_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.user_activecollab_settings ADD CONSTRAINT user_activecollab_settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.user_brands ADD CONSTRAINT user_brands_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES brands(id) ON DELETE CASCADE;
ALTER TABLE public.user_brands ADD CONSTRAINT user_brands_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.user_google_tokens ADD CONSTRAINT user_google_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.user_permissions ADD CONSTRAINT user_permissions_granted_by_fkey FOREIGN KEY (granted_by) REFERENCES users(id);
ALTER TABLE public.user_permissions ADD CONSTRAINT user_permissions_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.weekly_client_summary ADD CONSTRAINT weekly_client_summary_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id);
ALTER TABLE public.weekly_client_summary ADD CONSTRAINT weekly_client_summary_generated_by_fkey FOREIGN KEY (generated_by) REFERENCES users(id);
ALTER TABLE public.weekly_trends ADD CONSTRAINT weekly_trends_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
