GRANT ALL ON public.activecollab_credentials TO service_role;
GRANT ALL ON public.activecollab_sync_logs TO service_role;
GRANT ALL ON public.activecollab_task_data TO service_role;
GRANT ALL ON public.admin_google_drive_folders TO service_role;
GRANT ALL ON public.agent_memories TO service_role;
GRANT ALL ON public.ai_agent_knowledge_selection TO service_role;
GRANT ALL ON public.ai_agent_runs TO service_role;
GRANT ALL ON public.ai_agents TO service_role;
GRANT ALL ON public.ai_configurations TO service_role;
GRANT ALL ON public.ai_generated_images TO service_role;
GRANT ALL ON public.ai_shared_resources TO service_role;
GRANT ALL ON public.brand_analytics_data TO service_role;
GRANT ALL ON public.brand_analytics_integrations TO service_role;
GRANT ALL ON public.brand_file_comments TO service_role;
GRANT ALL ON public.brand_generated_posts TO service_role;
GRANT ALL ON public.brand_knowledge_files TO service_role;
GRANT ALL ON public.brand_kpis TO service_role;
GRANT ALL ON public.brands TO service_role;
GRANT ALL ON public.clients TO service_role;
GRANT ALL ON public.code_analysis_results TO service_role;
GRANT ALL ON public.code_generation_templates TO service_role;
GRANT ALL ON public.code_repositories TO service_role;
GRANT ALL ON public.collabai_agents TO service_role;
GRANT ALL ON public.contacts TO service_role;
GRANT ALL ON public.content_performance_metrics TO service_role;
GRANT ALL ON public.control_tower_api_keys TO service_role;
GRANT ALL ON public.control_tower_sync_logs TO service_role;
GRANT ALL ON public.deals TO service_role;
GRANT ALL ON public.documentation_output_config TO service_role;
GRANT ALL ON public.documentation_repository_links TO service_role;
GRANT ALL ON public.documentation_rules TO service_role;
GRANT ALL ON public.documentation_templates TO service_role;
GRANT ALL ON public.employee_user_mapping TO service_role;
GRANT ALL ON public.employees TO service_role;
GRANT ALL ON public.feedback_comments TO service_role;
GRANT ALL ON public.feedback_reports TO service_role;
GRANT ALL ON public.gemini_videos TO service_role;
GRANT ALL ON public.generated_posts TO service_role;
GRANT ALL ON public.gohighlevel_contacts TO service_role;
GRANT ALL ON public.gohighlevel_integrations TO service_role;
GRANT ALL ON public.google_drive_settings TO service_role;
GRANT ALL ON public.hackathon_events TO service_role;
GRANT ALL ON public.hackathon_judges TO service_role;
GRANT ALL ON public.hackathon_participants TO service_role;
GRANT ALL ON public.hackathon_scores TO service_role;
GRANT ALL ON public.hackathon_submissions TO service_role;
GRANT ALL ON public.hackathon_team_members TO service_role;
GRANT ALL ON public.hackathon_teams TO service_role;
GRANT ALL ON public.influencer_style_library TO service_role;
GRANT ALL ON public.integration_logs TO service_role;
GRANT ALL ON public.keyword_blog_usage TO service_role;
GRANT ALL ON public.keyword_ranking_history TO service_role;
GRANT ALL ON public.keyword_research TO service_role;
GRANT ALL ON public.keyword_suggestions TO service_role;
GRANT ALL ON public.knowledge_base TO service_role;
GRANT ALL ON public.knowledge_base_categories TO service_role;
GRANT ALL ON public.knowledge_base_files TO service_role;
GRANT ALL ON public.knowledge_files TO service_role;
GRANT ALL ON public.knowledge_sources TO service_role;
GRANT ALL ON public.leader_uploads TO service_role;
GRANT ALL ON public.linkedin_agent_templates TO service_role;
GRANT ALL ON public.linkedin_analytics_upload TO service_role;
GRANT ALL ON public.linkedin_content_metadata TO service_role;
GRANT ALL ON public.marketing_team_members TO service_role;
GRANT ALL ON public.n8n_workflow_configs TO service_role;
GRANT ALL ON public.n8n_workflow_executions TO service_role;
GRANT ALL ON public.newsletter_categories TO service_role;
GRANT ALL ON public.newsletter_sources TO service_role;
GRANT ALL ON public.organization_integrations TO service_role;
GRANT ALL ON public.organizations TO service_role;
GRANT ALL ON public.perplexity_settings TO service_role;
GRANT ALL ON public.pod_members TO service_role;
GRANT ALL ON public.pods TO service_role;
GRANT ALL ON public.post_agent_references TO service_role;
GRANT ALL ON public.project_knowledge_files TO service_role;
GRANT ALL ON public.project_meetings TO service_role;
GRANT ALL ON public.project_task_comments TO service_role;
GRANT ALL ON public.project_tasks TO service_role;
GRANT ALL ON public.projects TO service_role;
GRANT ALL ON public.quote_items TO service_role;
GRANT ALL ON public.quotes TO service_role;
GRANT ALL ON public.role_permissions TO service_role;
GRANT ALL ON public.seo_blog_content TO service_role;
GRANT ALL ON public.seo_reference_summaries TO service_role;
GRANT ALL ON public.sora_videos TO service_role;
GRANT ALL ON public.team_daily_summaries TO service_role;
GRANT ALL ON public.team_eod_submissions TO service_role;
GRANT ALL ON public.team_members TO service_role;
GRANT ALL ON public.teams TO service_role;
GRANT ALL ON public.testimonials TO service_role;
GRANT ALL ON public.thought_leaders TO service_role;
GRANT ALL ON public.user_accountability_chart TO service_role;
GRANT ALL ON public.user_activecollab_settings TO service_role;
GRANT ALL ON public.user_brands TO service_role;
GRANT ALL ON public.user_google_tokens TO service_role;
GRANT ALL ON public.user_permissions TO service_role;
GRANT ALL ON public.user_roles TO service_role;
GRANT ALL ON public.users TO service_role;
GRANT ALL ON public.vision_examples TO service_role;
GRANT ALL ON public.weekly_client_summary TO service_role;
GRANT ALL ON public.weekly_content_ideas TO service_role;
GRANT ALL ON public.weekly_trends TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.activecollab_credentials TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.activecollab_sync_logs TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.activecollab_task_data TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.admin_google_drive_folders TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.agent_memories TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ai_agent_knowledge_selection TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ai_agent_runs TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ai_agents TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ai_configurations TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ai_generated_images TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ai_shared_resources TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.brand_analytics_data TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.brand_analytics_integrations TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.brand_file_comments TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.brand_generated_posts TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.brand_knowledge_files TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.brand_kpis TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.brands TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.clients TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.code_analysis_results TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.code_generation_templates TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.code_repositories TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.collabai_agents TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.contacts TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.content_performance_metrics TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.control_tower_api_keys TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.control_tower_sync_logs TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.deals TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.documentation_output_config TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.documentation_repository_links TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.documentation_rules TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.documentation_templates TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.employee_user_mapping TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.employees TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.feedback_comments TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.feedback_reports TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.gemini_videos TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.generated_posts TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.gohighlevel_contacts TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.gohighlevel_integrations TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.google_drive_settings TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.hackathon_events TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.hackathon_judges TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.hackathon_participants TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.hackathon_scores TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.hackathon_submissions TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.hackathon_team_members TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.hackathon_teams TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.influencer_style_library TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.integration_logs TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.keyword_blog_usage TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.keyword_ranking_history TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.keyword_research TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.keyword_suggestions TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.knowledge_base TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.knowledge_base_categories TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.knowledge_base_files TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.knowledge_files TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.knowledge_sources TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.leader_uploads TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.linkedin_agent_templates TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.linkedin_analytics_upload TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.linkedin_content_metadata TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.marketing_team_members TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.n8n_workflow_configs TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.n8n_workflow_executions TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.newsletter_categories TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.newsletter_sources TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.organization_integrations TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.organizations TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.perplexity_settings TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pod_members TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pods TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.post_agent_references TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.project_knowledge_files TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.project_meetings TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.project_task_comments TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.project_tasks TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.projects TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.quote_items TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.quotes TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.role_permissions TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.seo_blog_content TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.seo_reference_summaries TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.sora_videos TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.team_daily_summaries TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.team_eod_submissions TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.team_members TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.teams TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.testimonials TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.thought_leaders TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_accountability_chart TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_activecollab_settings TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_brands TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_google_tokens TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_permissions TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_roles TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.users TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.vision_examples TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.weekly_client_summary TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.weekly_content_ideas TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.weekly_trends TO authenticated;
