CREATE POLICY "Admins manage ac creds" ON public.activecollab_credentials AS PERMISSIVE FOR ALL TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "Admins view ac creds" ON public.activecollab_credentials AS PERMISSIVE FOR SELECT TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "Admins view ac logs" ON public.activecollab_sync_logs AS PERMISSIVE FOR SELECT TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "System insert ac logs" ON public.activecollab_sync_logs AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth view ac tasks" ON public.activecollab_task_data AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admins view folders" ON public.admin_google_drive_folders AS PERMISSIVE FOR SELECT TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "Auth insert memories" ON public.agent_memories AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth view memories" ON public.agent_memories AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admins can manage agent knowledge selections" ON public.ai_agent_knowledge_selection AS PERMISSIVE FOR ALL TO public USING ((has_role(auth.uid(), 'super_admin'::text) OR has_role(auth.uid(), 'manager'::text))) WITH CHECK ((has_role(auth.uid(), 'super_admin'::text) OR has_role(auth.uid(), 'manager'::text)));
CREATE POLICY "Users can view agent knowledge selections" ON public.ai_agent_knowledge_selection AS PERMISSIVE FOR SELECT TO public USING ((has_role(auth.uid(), 'super_admin'::text) OR has_role(auth.uid(), 'manager'::text)));
CREATE POLICY "Auth insert runs" ON public.ai_agent_runs AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Users update own runs" ON public.ai_agent_runs AS PERMISSIVE FOR UPDATE TO authenticated USING (((executed_by = auth.uid()) OR has_role(auth.uid(), 'super_admin'::text)));
CREATE POLICY "Users view own runs" ON public.ai_agent_runs AS PERMISSIVE FOR SELECT TO authenticated USING (((executed_by = auth.uid()) OR has_role(auth.uid(), 'super_admin'::text)));
CREATE POLICY "Admins manage agents" ON public.ai_agents AS PERMISSIVE FOR ALL TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "Auth view agents" ON public.ai_agents AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admins manage config" ON public.ai_configurations AS PERMISSIVE FOR ALL TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "Auth view config" ON public.ai_configurations AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth create images" ON public.ai_generated_images AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth view images" ON public.ai_generated_images AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth view shared" ON public.ai_shared_resources AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Users view brand analytics" ON public.brand_analytics_data AS PERMISSIVE FOR SELECT TO authenticated USING (user_has_brand_access(auth.uid(), brand_id));
CREATE POLICY "Admins manage integrations" ON public.brand_analytics_integrations AS PERMISSIVE FOR ALL TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "Admins view integrations" ON public.brand_analytics_integrations AS PERMISSIVE FOR SELECT TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "Auth view bfc" ON public.brand_file_comments AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Users insert bfc" ON public.brand_file_comments AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((user_id = auth.uid()));
CREATE POLICY "Auth insert brand posts" ON public.brand_generated_posts AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Users view brand posts" ON public.brand_generated_posts AS PERMISSIVE FOR SELECT TO authenticated USING (user_has_brand_access(auth.uid(), brand_id));
CREATE POLICY "Admins manage brand knowledge" ON public.brand_knowledge_files AS PERMISSIVE FOR ALL TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "Users view brand knowledge" ON public.brand_knowledge_files AS PERMISSIVE FOR SELECT TO authenticated USING (user_has_brand_access(auth.uid(), brand_id));
CREATE POLICY "Admins manage kpis" ON public.brand_kpis AS PERMISSIVE FOR ALL TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "Users view kpis" ON public.brand_kpis AS PERMISSIVE FOR SELECT TO authenticated USING (user_has_brand_access(auth.uid(), brand_id));
CREATE POLICY "Admins manage brands" ON public.brands AS PERMISSIVE FOR ALL TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "Users view accessible brands" ON public.brands AS PERMISSIVE FOR SELECT TO authenticated USING (user_has_brand_access(auth.uid(), id));
CREATE POLICY "Admins manage clients" ON public.clients AS PERMISSIVE FOR ALL TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "Users view clients" ON public.clients AS PERMISSIVE FOR SELECT TO authenticated USING (user_has_client_access(auth.uid(), id));
CREATE POLICY "Auth view analysis" ON public.code_analysis_results AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth view cgt" ON public.code_generation_templates AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth view repos" ON public.code_repositories AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth view collabai" ON public.collabai_agents AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admins manage contacts" ON public.contacts AS PERMISSIVE FOR ALL TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "Auth view contacts" ON public.contacts AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth view cpm" ON public.content_performance_metrics AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admins view ct keys" ON public.control_tower_api_keys AS PERMISSIVE FOR SELECT TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "Admins view ct logs" ON public.control_tower_sync_logs AS PERMISSIVE FOR SELECT TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "Admins manage deals" ON public.deals AS PERMISSIVE FOR ALL TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "Auth view deals" ON public.deals AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth view doc" ON public.documentation_output_config AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth view drl" ON public.documentation_repository_links AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth view dr" ON public.documentation_rules AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth view dt" ON public.documentation_templates AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth view eum" ON public.employee_user_mapping AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admins manage employees" ON public.employees AS PERMISSIVE FOR ALL TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "Auth view employees" ON public.employees AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth view fb comments" ON public.feedback_comments AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Users insert fb comments" ON public.feedback_comments AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((user_id = auth.uid()));
CREATE POLICY "Users insert feedback" ON public.feedback_reports AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((user_id = auth.uid()));
CREATE POLICY "Users view own feedback" ON public.feedback_reports AS PERMISSIVE FOR SELECT TO authenticated USING (((user_id = auth.uid()) OR has_role(auth.uid(), 'super_admin'::text)));
CREATE POLICY "Auth create gv" ON public.gemini_videos AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth view gv" ON public.gemini_videos AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth insert posts" ON public.generated_posts AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth view posts" ON public.generated_posts AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admins view ghl" ON public.gohighlevel_contacts AS PERMISSIVE FOR SELECT TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "Admins view ghl int" ON public.gohighlevel_integrations AS PERMISSIVE FOR SELECT TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "Admins view gds" ON public.google_drive_settings AS PERMISSIVE FOR SELECT TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "Admins manage events" ON public.hackathon_events AS PERMISSIVE FOR ALL TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "Auth view events" ON public.hackathon_events AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth view hj" ON public.hackathon_judges AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth view participants" ON public.hackathon_participants AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Users register" ON public.hackathon_participants AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((user_id = auth.uid()));
CREATE POLICY "Auth view scores" ON public.hackathon_scores AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth insert hs" ON public.hackathon_submissions AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth view hs" ON public.hackathon_submissions AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth view htm" ON public.hackathon_team_members AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth insert ht" ON public.hackathon_teams AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth view ht" ON public.hackathon_teams AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth view styles" ON public.influencer_style_library AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admins view logs" ON public.integration_logs AS PERMISSIVE FOR SELECT TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "System insert logs" ON public.integration_logs AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Authenticated users can manage keyword_blog_usage" ON public.keyword_blog_usage AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Auth view kw ranking" ON public.keyword_ranking_history AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth view keywords" ON public.keyword_research AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated users can manage keyword_research" ON public.keyword_research AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Auth view kw suggest" ON public.keyword_suggestions AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated users can manage keyword_suggestions" ON public.keyword_suggestions AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Admins manage kb" ON public.knowledge_base AS PERMISSIVE FOR ALL TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "Auth view kb" ON public.knowledge_base AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admins manage kb cats" ON public.knowledge_base_categories AS PERMISSIVE FOR ALL TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "Auth view kb cats" ON public.knowledge_base_categories AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admins manage kb files" ON public.knowledge_base_files AS PERMISSIVE FOR ALL TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "Auth view kb files" ON public.knowledge_base_files AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admins manage kf" ON public.knowledge_files AS PERMISSIVE FOR ALL TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "Auth view kf" ON public.knowledge_files AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admins manage sources" ON public.knowledge_sources AS PERMISSIVE FOR ALL TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "Auth view sources" ON public.knowledge_sources AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth insert uploads" ON public.leader_uploads AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth view uploads" ON public.leader_uploads AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admins manage templates" ON public.linkedin_agent_templates AS PERMISSIVE FOR ALL TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "Auth view templates" ON public.linkedin_agent_templates AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth view li analytics" ON public.linkedin_analytics_upload AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth view lcm" ON public.linkedin_content_metadata AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth view mtm" ON public.marketing_team_members AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admins manage n8n" ON public.n8n_workflow_configs AS PERMISSIVE FOR ALL TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "Admins view n8n" ON public.n8n_workflow_configs AS PERMISSIVE FOR SELECT TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "Admins view executions" ON public.n8n_workflow_executions AS PERMISSIVE FOR SELECT TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "Auth view nl cats" ON public.newsletter_categories AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admins manage nl sources" ON public.newsletter_sources AS PERMISSIVE FOR ALL TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "Auth view nl sources" ON public.newsletter_sources AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admins view org int" ON public.organization_integrations AS PERMISSIVE FOR SELECT TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY organization_integrations_manage_authenticated ON public.organization_integrations AS PERMISSIVE FOR ALL TO authenticated USING ((auth.uid() IS NOT NULL)) WITH CHECK ((auth.uid() IS NOT NULL));
CREATE POLICY "Admins manage orgs" ON public.organizations AS PERMISSIVE FOR ALL TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "Auth can view orgs" ON public.organizations AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admins manage perp" ON public.perplexity_settings AS PERMISSIVE FOR ALL TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "Admins view perp" ON public.perplexity_settings AS PERMISSIVE FOR SELECT TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "Admins manage pm" ON public.pod_members AS PERMISSIVE FOR ALL TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "Auth view pm" ON public.pod_members AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admins manage pods" ON public.pods AS PERMISSIVE FOR ALL TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "Auth view pods" ON public.pods AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth view refs" ON public.post_agent_references AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth view pkf" ON public.project_knowledge_files AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth insert meetings" ON public.project_meetings AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth view meetings" ON public.project_meetings AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth insert comments" ON public.project_task_comments AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((created_by = auth.uid()));
CREATE POLICY "Auth view comments" ON public.project_task_comments AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth insert tasks" ON public.project_tasks AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth view tasks" ON public.project_tasks AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Users update own tasks" ON public.project_tasks AS PERMISSIVE FOR UPDATE TO authenticated USING (((assigned_to = auth.uid()) OR has_role(auth.uid(), 'super_admin'::text) OR has_role(auth.uid(), 'pm'::text)));
CREATE POLICY "Admins manage projects" ON public.projects AS PERMISSIVE FOR ALL TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "Users view projects" ON public.projects AS PERMISSIVE FOR SELECT TO public USING ((auth.uid() IS NOT NULL));
CREATE POLICY "Auth insert qi" ON public.quote_items AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth view qi" ON public.quote_items AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth insert quotes" ON public.quotes AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth view quotes" ON public.quotes AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth view role perms" ON public.role_permissions AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth insert seo" ON public.seo_blog_content AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth view seo" ON public.seo_blog_content AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Users can create blogs" ON public.seo_blog_content AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can delete own blogs" ON public.seo_blog_content AS PERMISSIVE FOR DELETE TO public USING ((auth.uid() = user_id));
CREATE POLICY "Users can update own blogs" ON public.seo_blog_content AS PERMISSIVE FOR UPDATE TO public USING ((auth.uid() = user_id));
CREATE POLICY "Users can view own blogs" ON public.seo_blog_content AS PERMISSIVE FOR SELECT TO public USING ((auth.uid() = user_id));
CREATE POLICY "Auth view seo refs" ON public.seo_reference_summaries AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth create sv" ON public.sora_videos AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth view sv" ON public.sora_videos AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth view summaries" ON public.team_daily_summaries AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Users insert own eod" ON public.team_eod_submissions AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((user_id = auth.uid()));
CREATE POLICY "Users view own eod" ON public.team_eod_submissions AS PERMISSIVE FOR SELECT TO authenticated USING (((user_id = auth.uid()) OR has_role(auth.uid(), 'super_admin'::text) OR has_role(auth.uid(), 'manager'::text)));
CREATE POLICY "Auth view tm" ON public.team_members AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth view teams" ON public.teams AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth insert" ON public.testimonials AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Auth view all" ON public.testimonials AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Public view approved" ON public.testimonials AS PERMISSIVE FOR SELECT TO public USING ((is_approved = true));
CREATE POLICY "Admins manage leaders" ON public.thought_leaders AS PERMISSIVE FOR ALL TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "Auth view leaders" ON public.thought_leaders AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Users manage own chart" ON public.user_accountability_chart AS PERMISSIVE FOR ALL TO authenticated USING (((user_id = auth.uid()) OR has_role(auth.uid(), 'super_admin'::text)));
CREATE POLICY "Users view own chart" ON public.user_accountability_chart AS PERMISSIVE FOR SELECT TO authenticated USING (((user_id = auth.uid()) OR has_role(auth.uid(), 'super_admin'::text)));
CREATE POLICY "Users manage own ac" ON public.user_activecollab_settings AS PERMISSIVE FOR ALL TO authenticated USING ((user_id = auth.uid()));
CREATE POLICY "Users view own ac" ON public.user_activecollab_settings AS PERMISSIVE FOR SELECT TO authenticated USING ((user_id = auth.uid()));
CREATE POLICY "Admins manage brand access" ON public.user_brands AS PERMISSIVE FOR ALL TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "Users view own brand access" ON public.user_brands AS PERMISSIVE FOR SELECT TO authenticated USING (((user_id = auth.uid()) OR has_role(auth.uid(), 'super_admin'::text)));
CREATE POLICY "Users manage own tokens" ON public.user_google_tokens AS PERMISSIVE FOR ALL TO authenticated USING ((user_id = auth.uid()));
CREATE POLICY "Users view own tokens" ON public.user_google_tokens AS PERMISSIVE FOR SELECT TO authenticated USING ((user_id = auth.uid()));
CREATE POLICY "Admins manage perms" ON public.user_permissions AS PERMISSIVE FOR ALL TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "Users view own perms" ON public.user_permissions AS PERMISSIVE FOR SELECT TO authenticated USING ((user_id = auth.uid()));
CREATE POLICY "Admins can manage roles" ON public.user_roles AS PERMISSIVE FOR ALL TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "Users can view own roles" ON public.user_roles AS PERMISSIVE FOR SELECT TO authenticated USING (((user_id = auth.uid()) OR has_role(auth.uid(), 'super_admin'::text)));
CREATE POLICY "Admins can manage users" ON public.users AS PERMISSIVE FOR ALL TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "System can insert users" ON public.users AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Users can update own profile" ON public.users AS PERMISSIVE FOR UPDATE TO authenticated USING ((id = auth.uid()));
CREATE POLICY "Users can view all users" ON public.users AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth view ve" ON public.vision_examples AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth view wcs" ON public.weekly_client_summary AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth insert content ideas" ON public.weekly_content_ideas AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.uid() IS NOT NULL));
CREATE POLICY "Auth view content ideas" ON public.weekly_content_ideas AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "Admins manage trends" ON public.weekly_trends AS PERMISSIVE FOR ALL TO authenticated USING (has_role(auth.uid(), 'super_admin'::text));
CREATE POLICY "Auth view trends" ON public.weekly_trends AS PERMISSIVE FOR SELECT TO authenticated USING (true);
