#!/usr/bin/env bash
set -e
# Usage: DATABASE_URL=postgres://... bash 12_data_load.sh
: "${DATABASE_URL:?set DATABASE_URL}"
SET_TRIGGERS_OFF="SET session_replication_role = replica;"
cd "$(dirname "$0")/11_data"
psql "$DATABASE_URL" -c "\copy public.\"activecollab_task_data\" FROM 'activecollab_task_data.csv' WITH CSV HEADER"
psql "$DATABASE_URL" -c "\copy public.\"ai_agent_knowledge_selection\" FROM 'ai_agent_knowledge_selection.csv' WITH CSV HEADER"
psql "$DATABASE_URL" -c "\copy public.\"ai_agent_runs\" FROM 'ai_agent_runs.csv' WITH CSV HEADER"
psql "$DATABASE_URL" -c "\copy public.\"ai_agents\" FROM 'ai_agents.csv' WITH CSV HEADER"
psql "$DATABASE_URL" -c "\copy public.\"ai_configurations\" FROM 'ai_configurations.csv' WITH CSV HEADER"
psql "$DATABASE_URL" -c "\copy public.\"ai_generated_images\" FROM 'ai_generated_images.csv' WITH CSV HEADER"
psql "$DATABASE_URL" -c "\copy public.\"brand_analytics_data\" FROM 'brand_analytics_data.csv' WITH CSV HEADER"
psql "$DATABASE_URL" -c "\copy public.\"brand_generated_posts\" FROM 'brand_generated_posts.csv' WITH CSV HEADER"
psql "$DATABASE_URL" -c "\copy public.\"brand_kpis\" FROM 'brand_kpis.csv' WITH CSV HEADER"
psql "$DATABASE_URL" -c "\copy public.\"brands\" FROM 'brands.csv' WITH CSV HEADER"
psql "$DATABASE_URL" -c "\copy public.\"clients\" FROM 'clients.csv' WITH CSV HEADER"
psql "$DATABASE_URL" -c "\copy public.\"contacts\" FROM 'contacts.csv' WITH CSV HEADER"
psql "$DATABASE_URL" -c "\copy public.\"content_performance_metrics\" FROM 'content_performance_metrics.csv' WITH CSV HEADER"
psql "$DATABASE_URL" -c "\copy public.\"deals\" FROM 'deals.csv' WITH CSV HEADER"
psql "$DATABASE_URL" -c "\copy public.\"employees\" FROM 'employees.csv' WITH CSV HEADER"
psql "$DATABASE_URL" -c "\copy public.\"generated_posts\" FROM 'generated_posts.csv' WITH CSV HEADER"
psql "$DATABASE_URL" -c "\copy public.\"hackathon_events\" FROM 'hackathon_events.csv' WITH CSV HEADER"
psql "$DATABASE_URL" -c "\copy public.\"hackathon_participants\" FROM 'hackathon_participants.csv' WITH CSV HEADER"
psql "$DATABASE_URL" -c "\copy public.\"hackathon_submissions\" FROM 'hackathon_submissions.csv' WITH CSV HEADER"
psql "$DATABASE_URL" -c "\copy public.\"hackathon_teams\" FROM 'hackathon_teams.csv' WITH CSV HEADER"
psql "$DATABASE_URL" -c "\copy public.\"keyword_research\" FROM 'keyword_research.csv' WITH CSV HEADER"
psql "$DATABASE_URL" -c "\copy public.\"knowledge_base\" FROM 'knowledge_base.csv' WITH CSV HEADER"
psql "$DATABASE_URL" -c "\copy public.\"knowledge_base_categories\" FROM 'knowledge_base_categories.csv' WITH CSV HEADER"
psql "$DATABASE_URL" -c "\copy public.\"n8n_workflow_configs\" FROM 'n8n_workflow_configs.csv' WITH CSV HEADER"
psql "$DATABASE_URL" -c "\copy public.\"newsletter_sources\" FROM 'newsletter_sources.csv' WITH CSV HEADER"
psql "$DATABASE_URL" -c "\copy public.\"organization_integrations\" FROM 'organization_integrations.csv' WITH CSV HEADER"
psql "$DATABASE_URL" -c "\copy public.\"organizations\" FROM 'organizations.csv' WITH CSV HEADER"
psql "$DATABASE_URL" -c "\copy public.\"pod_members\" FROM 'pod_members.csv' WITH CSV HEADER"
psql "$DATABASE_URL" -c "\copy public.\"pods\" FROM 'pods.csv' WITH CSV HEADER"
psql "$DATABASE_URL" -c "\copy public.\"project_task_comments\" FROM 'project_task_comments.csv' WITH CSV HEADER"
psql "$DATABASE_URL" -c "\copy public.\"project_tasks\" FROM 'project_tasks.csv' WITH CSV HEADER"
psql "$DATABASE_URL" -c "\copy public.\"projects\" FROM 'projects.csv' WITH CSV HEADER"
psql "$DATABASE_URL" -c "\copy public.\"seo_blog_content\" FROM 'seo_blog_content.csv' WITH CSV HEADER"
psql "$DATABASE_URL" -c "\copy public.\"sora_videos\" FROM 'sora_videos.csv' WITH CSV HEADER"
psql "$DATABASE_URL" -c "\copy public.\"team_eod_submissions\" FROM 'team_eod_submissions.csv' WITH CSV HEADER"
psql "$DATABASE_URL" -c "\copy public.\"team_members\" FROM 'team_members.csv' WITH CSV HEADER"
psql "$DATABASE_URL" -c "\copy public.\"teams\" FROM 'teams.csv' WITH CSV HEADER"
psql "$DATABASE_URL" -c "\copy public.\"thought_leaders\" FROM 'thought_leaders.csv' WITH CSV HEADER"
psql "$DATABASE_URL" -c "\copy public.\"user_brands\" FROM 'user_brands.csv' WITH CSV HEADER"
psql "$DATABASE_URL" -c "\copy public.\"user_roles\" FROM 'user_roles.csv' WITH CSV HEADER"
psql "$DATABASE_URL" -c "\copy public.\"users\" FROM 'users.csv' WITH CSV HEADER"
psql "$DATABASE_URL" -c "\copy public.\"weekly_client_summary\" FROM 'weekly_client_summary.csv' WITH CSV HEADER"
